[tools]
go = "latest"
golangci-lint = "latest"
ripgrep = "latest"
shellcheck = "latest"

[env]
# https://mise.jdx.dev/environments/#env-path
GOBIN = "{{config_root}}/bin"
_.path = ["{{env.GOBIN}}"]

[tasks]
test = "go test -coverprofile=.coverage ./..."
golangci-lint = "golangci-lint run ./..."
shellcheck = "shellcheck ./scripts/*.sh"
fmt = "golangci-lint fmt ./..."
fmt-check = "golangci-lint fmt --diff ./..."

[tasks.lint]
depends = ["golangci-lint", "shellcheck", "fmt-check"]


[tasks.ci]
depends = ["lint", "test"]


[tasks.coverage]
depends = ["test"]
run = "go tool cover -html=.coverage -o coverage.html"
